region             = "eu-north-1"
backup_region      = "eu-west-3"
profile            = "default"
nexus_bucket_name  = "nexus-bucket-si-2021"
backup_bucket_name = "backup-bucket-for-nexus-project"
java_rpm_file_name = "mc-4.8.7-11.el7.x86_64.rpm"
